version: 0.2

phases:
  build:
    commands:
      - echo "Packaging index-photos..."
      - cd backend/index-photos
      - zip -r ../../index-photos.zip .
      - cd ../../
      - echo "Packaging search-photos..."
      - cd backend/search-photos
      - zip -r ../../search-photos.zip .
      - cd ../../
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
  base-directory: . 
  discard-paths: yes
